services:
  - type: web
    name: speakyz-bot
    env: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: WEBSITE_URL
        value: "https://sites.google.com/view/wwwspeakzycom"
      - key: PORT
        value: "10000"
      - key: RENDER
        value: "true"